### ISSUE TITLE
Issue with Custom Paper Size (65mm x 65mm) on Sunmi V2s PLUS Using Ionic Capacitor Plugin

### ISSUE THREAD

**Issue by Dipeshjayswal** [kduma-autoid/capacitor-sunmi-printer#17]
Helllo @kduma and @gandalfthegreydev 

I am using your plugin in my Ionic Capacitor project with the **Sunmi V2s PLUS** device, and it has been working well with the default paper size of 75mm x 75mm. However, I need to use a custom paper size of 65mm x 65mm.

**When I attempt to print with this custom paper size, I encounter the following issues:**
  1. Characters are getting cut off.
  2. Alignment is not proper.
  
It seems that the plugin does not provide an option to set or customize the paper width and height.

**Expected Behavior**:  The printed content should fit properly on the custom paper size of 65mm x 65mm with no characters being cut off and proper alignment.

**Actual Behavior**: Characters are getting cut off, and the alignment is not correct when printing on custom-sized paper.

**Device and Setup Details**:
 1. Device: Sunmi V2s PLUS
 2. Default paper size: 75mm x 75mm (works fine)
 3. Custom paper size: 65mm x 65mm (causes issues)
 4. Framework: Ionic Capacitor
 5. **Pritinter Type : Label Printer**
 
 **Request** :  Could you please provide a solution to set custom paper width and height through the plugin? If not already supported, can this feature be added? Alternatively, if there are any workarounds or configurations to resolve this issue, please let me know.

 Additionally, it would be great to have documentation or examples showing how to configure custom paper sizes using this plugin.

65mm * 65mm : 
![shared image](https://github.com/user-attachments/assets/33d12217-c891-4c0d-8cd4-555c57dec44c)

I wan

Thank you for your support!

**Comment by Dipeshjayswal** [comment]
and, Fore more information, Sunmi Inner Printer is provided only two paper sizes 58mm & 80mm.

**Comment by kduma** [comment]
Hello,

I think that there are two ESC/POS commands that you can use which could work (although supported commands differ from one device to another):

- `GS W nL nH` - Set printing area width
- `GS LnL nH` - Set left margin

Sunmi ESC/POS documentation is here: https://ota.cdn.sunmi.com/DOC/resource/re_en/ESC-POS%20Command%20set.docx

When I will have some time available, I will test it. 

On the other hand, newer Sunmi models support the TSPL print language, which is designed for printing labels - maybe that direction is something you could consider (but at the moment I don’t have an compatible SDK ready)

**Comment by kduma** [comment]
Hello,

I have added two above methods:

- [`SetPrintingAreaWidth(...)`](https://github.com/kduma-autoid/capacitor-sunmi-printer?tab=readme-ov-file#setprintingareawidth)
- [`SetLeftMargin(...)`](https://github.com/kduma-autoid/capacitor-sunmi-printer?tab=readme-ov-file#setleftmargin)

I have tested it on a printer of T3 Pro Max and it works like on attached pictures. 

**Default setting:**
![default printout](https://github.com/user-attachments/assets/96764db5-bb80-4b0b-95aa-450217d551b5)

**`SetLeftMargin({width: 200})`**
![margin equals 200](https://github.com/user-attachments/assets/abef122f-4e3d-4be5-8d49-476897fee858)

**`SetPrintingAreaWidth({width: 300})`**
![width equals 300](https://github.com/user-attachments/assets/fe9b3863-4b9f-4063-8175-d7ee0c3944b3)



-------------------

You can test it on the your V2SPlus device, but as those printers have different firmware (even between manufacturing series of the same model), I cannot guarantee that it will work - milage may vary.

For best experience of generating and printing of labels, I would go of the way to print using TSPL print language or generate bitmap of correct size, and print the bitmap instead.
