### ISSUE TITLE
Add listeners for events happening with print device

### ISSUE THREAD

**Issue by kduma** [kduma-autoid/capacitor-sunmi-printer#3]

**Comment by kreare** [comment]
I would suppose that this feature is to get notifications when events occurs without having to poll the printer state at defined intervals (like 2 seconds or so), right ?

Because i was here to ask for this (and I'm unable to do on my own)

Being notified just for an out-of-paper event would be great.

**Comment by kduma** [comment]
Accordning to [Sunmi Printer documentation](https://developer.sunmi.com/docs/en-US/xeghjk491/ciqeghjk513), "Appendix A: Printing service broadcast", there are following notifiable events broadcasted:

Function | Action
-- | --
Printer is under preparation | "woyou.aidlservice.jiuv5.INIT_ACTION"
Printer is updating | "woyou.aidlservice.jiuv5.FIRMWARE_UPDATING_ACITON"
Printing is ready | "woyou.aidlservice.jiuv5.NORMAL_ACTION"
Printing error | "woyou.aidlservice.jiuv5.ERROR_ACTION"
Out of paper | "woyou.aidlservice.jiuv5.OUT_OF_PAPER_ACTION"
Printhead is overheated | "woyou.aidlservice.jiuv5.OVER_HEATING_ACITON"
Printhead temperature back to normal | "woyou.aidlservice.jiuv5.NORMAL_HEATING_ACITON"
Cover open | "woyou.aidlservice.jiuv5.COVER_OPEN_ACTION"
Cover closing exception | "woyou.aidlservice.jiuv5.COVER_ERROR_ACTION"
Cutter exception 1 – cutter stuck | "woyou.aidlservice.jiuv5.KNIFE_ERROR_ACTION_1"
Cutter exception 2 – cutter back to normal | "woyou.aidlservice.jiuv5.KNIFE_ERROR_ACTION_2"
Printer firmware updating | "woyou.aidlservice.jiuv5.FIRMWARE_UPDATING_ACITON"
Printer firmware updating failed | "woyou.aidlservice.jiuv5.FIRMWARE_FAILURE_ACITON"
Printer not detected | "woyou.aidlservice.jiuv5.PRINTER_NON_EXISTENT_ACITON"
Black mark not detected | "woyou.aidlservice.jiuv5.BLACKLABEL_NON_EXISTENT_ACITON"

**Comment by kreare** [comment]
ok but how to listen for these events?
