### ISSUE TITLE
Capacitor 6.x compatibility

### ISSUE THREAD

**Issue by guestisp** [kduma-autoid/capacitor-sunmi-printer#6]
Any plans to migrate to Capacitor v6 ?

**Comment by kduma** [comment]
At this moment my plugins (except one) are not yet updated for capacitor 6.x. I will be updating them while upgrading my apps, which depends on them. But feel free to make a pull request if you need it quicker - one plugin already got community contribution to update. :)

**Comment by kreare** [comment]
Done :-)
