### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by kreare** [kduma-autoid/capacitor-sunmi-printer#8]
im migrating an old Cordova app to Capacitor and this plugin, but my old code doesn't work at all (method names are mostly the same but the print doesn't work)

can you put a small but working example? like an "hello Word" print

**Comment by kduma** [comment]
Hi @kreare,

I have added a usage examples to the [readme](https://github.com/kduma-autoid/capacitor-sunmi-printer?tab=readme-ov-file#example-usage) and [demo app](https://github.com/kduma-autoid/capacitor-sunmi-printer/blob/9b5f34f9dc10d15cdd90bf77e51edd52f59084de/example/src/js/capacitor-welcome.js#L292-L336).
