### ISSUE TITLE
Print PDF

### ISSUE THREAD

**Issue by amuedojulian** [kduma-autoid/capacitor-sunmi-printer#9]
@kduma  Hello! I need to send a PDF to the internal printer so it can print, how do I do it?

**Comment by kduma** [comment]
Hi @amuedojulian,

Sunmi devices doesn't support natively printing of PDF files. So if you want to print a PDF, you need to first convert it to a bitmap (image) which you can later print using [printbitmap](https://github.com/kduma-autoid/capacitor-sunmi-printer?tab=readme-ov-file#printbitmap) method.
